#!/usr/bin/env node
import { createClient } from '@supabase/supabase-js';
import { readFileSync } from 'fs';

const SUPABASE_URL = 'https://mxboigeahudnbigxgefp.supabase.co';
const SUPABASE_ANON_KEY = process.env.VITE_SUPABASE_ANON_KEY || 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im14Ym9pZ2VhaHVkbmJpZ3hnZWZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzU5MTQ5NzIsImV4cCI6MjA1MTQ5MDk3Mn0.ZrQNzONhctOVJkfxPaT4Fpp2Lf7yRMGpgUDqFNTSCak';

const supabase = createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

// Complete storage data for all 20 systems
const storageData = [
  {
    slug: 'byd-battery-box-premium-hvs',
    brand: 'BYD',
    model: 'Battery-Box Premium',
    variant: 'HVS',
    production_location: 'China',
    production_country: 'China',
    module_capacity_kwh: 2.56,
    min_modules: 2,
    max_modules: 5,
    total_capacity_min_kwh: 5.12,
    total_capacity_max_kwh: 12.80,
    cell_technology: 'LFP',
    cycle_life: 6000,
    depth_of_discharge_pct: 90,
    efficiency_pct: 96.0,
    charge_power_kw: 3.5,
    discharge_power_kw: 3.5,
    continuous_power_kw: 3.5,
    peak_power_kw: 5.0,
    compatible_inverters: ['Fronius', 'SMA', 'Kostal', 'Goodwe'],
    inverter_type: 'DC-coupled',
    backup_capable: true,
    mounting_type: 'Wall',
    dimensions_h_mm: 713,
    dimensions_w_mm: 600,
    dimensions_d_mm: 220,
    weight_kg: 36,
    ip_rating: 'IP55',
    operating_temp_min_c: -10,
    operating_temp_max_c: 50,
    price_per_module_eur: 2490,
    installation_cost_eur: 1200,
    warranty_years: 10,
    warranty_cycles: 6000,
    warranty_capacity_retention_pct: 80,
    has_app: true,
    has_energy_management: true,
    supports_solar: true,
    supports_grid_services: false,
    status: 'Available',
    release_year: 2020,
    certifications: ['CE', 'VDE', 'IEC 62619'],
    description: 'High-quality LFP storage system with excellent scalability and proven reliability.',
    manufacturer_url: 'https://www.byd.com'
  },
  {
    slug: 'sonnenbatterie-10',
    brand: 'sonnen',
    model: 'sonnenBatterie',
    variant: '10',
    production_location: 'Germany',
    production_country: 'Germany',
    module_capacity_kwh: 5.5,
    min_modules: 2,
    max_modules: 6,
    total_capacity_min_kwh: 11.0,
    total_capacity_max_kwh: 33.0,
    cell_technology: 'LFP',
    cycle_life: 10000,
    depth_of_discharge_pct: 100,
    efficiency_pct: 93.0,
    charge_power_kw: 4.6,
    discharge_power_kw: 4.6,
    continuous_power_kw: 4.6,
    peak_power_kw: 8.0,
    compatible_inverters: ['sonnen inverter (integrated)'],
    inverter_type: 'All-in-one',
    backup_capable: true,
    mounting_type: 'Floor',
    dimensions_h_mm: 1670,
    dimensions_w_mm: 660,
    dimensions_d_mm: 280,
    weight_kg: 120,
    ip_rating: 'IP20',
    operating_temp_min_c: 0,
    operating_temp_max_c: 35,
    price_per_module_eur: 6500,
    installation_cost_eur: 2500,
    warranty_years: 10,
    warranty_cycles: 10000,
    warranty_capacity_retention_pct: 70,
    has_app: true,
    has_energy_management: true,
    supports_solar: true,
    supports_grid_services: true,
    status: 'Available',
    release_year: 2021,
    certifications: ['CE', 'VDE'],
    description: 'Premium German-made all-in-one system with virtual power plant capabilities.',
    manufacturer_url: 'https://sonnen.de'
  },
  {
    slug: 'e3dc-s10-e-pro',
    brand: 'E3/DC',
    model: 'S10 E',
    variant: 'PRO',
    production_location: 'Germany',
    production_country: 'Germany',
    module_capacity_kwh: 6.5,
    min_modules: 1,
    max_modules: 4,
    total_capacity_min_kwh: 6.5,
    total_capacity_max_kwh: 26.0,
    cell_technology: 'NMC',
    cycle_life: 7000,
    depth_of_discharge_pct: 95,
    efficiency_pct: 94.5,
    charge_power_kw: 9.2,
    discharge_power_kw: 9.2,
    continuous_power_kw: 9.2,
    peak_power_kw: 13.8,
    compatible_inverters: ['E3/DC (integrated)'],
    inverter_type: 'All-in-one',
    backup_capable: true,
    mounting_type: 'Floor',
    dimensions_h_mm: 1655,
    dimensions_w_mm: 680,
    dimensions_d_mm: 295,
    weight_kg: 140,
    ip_rating: 'IP20',
    operating_temp_min_c: 0,
    operating_temp_max_c: 40,
    price_per_module_eur: 7800,
    installation_cost_eur: 3000,
    warranty_years: 10,
    warranty_cycles: 7000,
    warranty_capacity_retention_pct: 80,
    has_app: true,
    has_energy_management: true,
    supports_solar: true,
    supports_grid_services: true,
    status: 'Available',
    release_year: 2019,
    certifications: ['CE', 'VDE', 'IEC 62619'],
    description: 'Premium all-in-one system with AI-based energy management and emergency power function.',
    manufacturer_url: 'https://www.e3dc.com'
  },
  {
    slug: 'rct-power-battery',
    brand: 'RCT Power',
    model: 'Power Battery',
    variant: null,
    production_location: 'Germany',
    production_country: 'Germany',
    module_capacity_kwh: 5.12,
    min_modules: 1,
    max_modules: 6,
    total_capacity_min_kwh: 5.12,
    total_capacity_max_kwh: 30.72,
    cell_technology: 'LFP',
    cycle_life: 6000,
    depth_of_discharge_pct: 90,
    efficiency_pct: 95.0,
    charge_power_kw: 5.0,
    discharge_power_kw: 5.0,
    continuous_power_kw: 5.0,
    peak_power_kw: 7.5,
    compatible_inverters: ['RCT Power inverters'],
    inverter_type: 'DC-coupled',
    backup_capable: true,
    mounting_type: 'Floor',
    dimensions_h_mm: 900,
    dimensions_w_mm: 600,
    dimensions_d_mm: 230,
    weight_kg: 65,
    ip_rating: 'IP20',
    operating_temp_min_c: -10,
    operating_temp_max_c: 50,
    price_per_module_eur: 3200,
    installation_cost_eur: 1500,
    warranty_years: 10,
    warranty_cycles: 6000,
    warranty_capacity_retention_pct: 80,
    has_app: true,
    has_energy_management: true,
    supports_solar: true,
    supports_grid_services: false,
    status: 'Available',
    release_year: 2020,
    certifications: ['CE', 'VDE'],
    description: 'German-engineered LFP system with high efficiency and flexible scalability.',
    manufacturer_url: 'https://www.rct-power.com'
  },
  {
    slug: 'senec-home-v3-hybrid',
    brand: 'SENEC',
    model: 'Home V3',
    variant: 'hybrid',
    production_location: 'Germany',
    production_country: 'Germany',
    module_capacity_kwh: 5.0,
    min_modules: 1,
    max_modules: 4,
    total_capacity_min_kwh: 5.0,
    total_capacity_max_kwh: 20.0,
    cell_technology: 'LFP',
    cycle_life: 10000,
    depth_of_discharge_pct: 100,
    efficiency_pct: 94.0,
    charge_power_kw: 5.0,
    discharge_power_kw: 5.0,
    continuous_power_kw: 5.0,
    peak_power_kw: 7.5,
    compatible_inverters: ['SENEC (integrated)'],
    inverter_type: 'All-in-one',
    backup_capable: true,
    mounting_type: 'Floor',
    dimensions_h_mm: 1260,
    dimensions_w_mm: 650,
    dimensions_d_mm: 300,
    weight_kg: 110,
    ip_rating: 'IP20',
    operating_temp_min_c: 0,
    operating_temp_max_c: 40,
    price_per_module_eur: 5500,
    installation_cost_eur: 2200,
    warranty_years: 10,
    warranty_cycles: 10000,
    warranty_capacity_retention_pct: 70,
    has_app: true,
    has_energy_management: true,
    supports_solar: true,
    supports_grid_services: true,
    status: 'Available',
    release_year: 2020,
    certifications: ['CE', 'VDE'],
    description: 'All-in-one system with cloud integration and virtual power plant participation.',
    manufacturer_url: 'https://senec.com'
  },
  {
    slug: 'tesla-powerwall-3',
    brand: 'Tesla',
    model: 'Powerwall',
    variant: '3',
    production_location: 'China',
    production_country: 'China',
    module_capacity_kwh: 13.5,
    min_modules: 1,
    max_modules: 3,
    total_capacity_min_kwh: 13.5,
    total_capacity_max_kwh: 40.5,
    cell_technology: 'LFP',
    cycle_life: 3750,
    depth_of_discharge_pct: 100,
    efficiency_pct: 90.0,
    charge_power_kw: 11.5,
    discharge_power_kw: 11.5,
    continuous_power_kw: 11.5,
    peak_power_kw: 17.5,
    compatible_inverters: ['Tesla (integrated)'],
    inverter_type: 'All-in-one',
    backup_capable: true,
    mounting_type: 'Wall',
    dimensions_h_mm: 1098,
    dimensions_w_mm: 609,
    dimensions_d_mm: 193,
    weight_kg: 130,
    ip_rating: 'IP67',
    operating_temp_min_c: -20,
    operating_temp_max_c: 50,
    price_per_module_eur: 9500,
    installation_cost_eur: 3000,
    warranty_years: 10,
    warranty_cycles: 3750,
    warranty_capacity_retention_pct: 70,
    has_app: true,
    has_energy_management: true,
    supports_solar: true,
    supports_grid_services: false,
    status: 'Available',
    release_year: 2024,
    certifications: ['CE', 'IEC 62619'],
    description: 'High-capacity all-in-one system with integrated solar inverter and exceptional power output.',
    manufacturer_url: 'https://www.tesla.com/powerwall'
  },
  {
    slug: 'lg-chem-resu-10h',
    brand: 'LG Chem',
    model: 'RESU',
    variant: '10H',
    production_location: 'Europe',
    production_country: 'Poland',
    module_capacity_kwh: 9.8,
    min_modules: 1,
    max_modules: 1,
    total_capacity_min_kwh: 9.8,
    total_capacity_max_kwh: 9.8,
    cell_technology: 'NMC',
    cycle_life: 6000,
    depth_of_discharge_pct: 90,
    efficiency_pct: 95.0,
    charge_power_kw: 5.0,
    discharge_power_kw: 5.0,
    continuous_power_kw: 5.0,
    peak_power_kw: 7.0,
    compatible_inverters: ['SMA', 'Fronius', 'SolarEdge', 'Kostal'],
    inverter_type: 'DC-coupled',
    backup_capable: false,
    mounting_type: 'Wall',
    dimensions_h_mm: 693,
    dimensions_w_mm: 452,
    dimensions_d_mm: 226,
    weight_kg: 78,
    ip_rating: 'IP55',
    operating_temp_min_c: -10,
    operating_temp_max_c: 45,
    price_per_module_eur: 5800,
    installation_cost_eur: 1500,
    warranty_years: 10,
    warranty_cycles: 6000,
    warranty_capacity_retention_pct: 60,
    has_app: false,
    has_energy_management: false,
    supports_solar: true,
    supports_grid_services: false,
    status: 'Available',
    release_year: 2017,
    certifications: ['CE', 'IEC 62619'],
    description: 'Compact high-voltage battery with wide inverter compatibility.',
    manufacturer_url: 'https://www.lg.com'
  },
  {
    slug: 'varta-pulse-neo',
    brand: 'VARTA',
    model: 'pulse',
    variant: 'neo',
    production_location: 'Germany',
    production_country: 'Germany',
    module_capacity_kwh: 6.5,
    min_modules: 1,
    max_modules: 4,
    total_capacity_min_kwh: 6.5,
    total_capacity_max_kwh: 26.0,
    cell_technology: 'LFP',
    cycle_life: 6000,
    depth_of_discharge_pct: 90,
    efficiency_pct: 93.0,
    charge_power_kw: 7.0,
    discharge_power_kw: 7.0,
    continuous_power_kw: 7.0,
    peak_power_kw: 10.5,
    compatible_inverters: ['VARTA element (integrated)'],
    inverter_type: 'All-in-one',
    backup_capable: true,
    mounting_type: 'Floor',
    dimensions_h_mm: 1455,
    dimensions_w_mm: 550,
    dimensions_d_mm: 280,
    weight_kg: 115,
    ip_rating: 'IP20',
    operating_temp_min_c: 0,
    operating_temp_max_c: 40,
    price_per_module_eur: 6200,
    installation_cost_eur: 2000,
    warranty_years: 10,
    warranty_cycles: 6000,
    warranty_capacity_retention_pct: 80,
    has_app: true,
    has_energy_management: true,
    supports_solar: true,
    supports_grid_services: false,
    status: 'Available',
    release_year: 2022,
    certifications: ['CE', 'VDE'],
    description: 'German quality all-in-one system with AI-based optimization and emergency power.',
    manufacturer_url: 'https://www.varta-ag.com'
  },
  {
    slug: 'huawei-luna2000',
    brand: 'Huawei',
    model: 'LUNA2000',
    variant: null,
    production_location: 'China',
    production_country: 'China',
    module_capacity_kwh: 5.0,
    min_modules: 1,
    max_modules: 6,
    total_capacity_min_kwh: 5.0,
    total_capacity_max_kwh: 30.0,
    cell_technology: 'LFP',
    cycle_life: 6000,
    depth_of_discharge_pct: 100,
    efficiency_pct: 96.5,
    charge_power_kw: 5.0,
    discharge_power_kw: 5.0,
    continuous_power_kw: 5.0,
    peak_power_kw: 6.5,
    compatible_inverters: ['Huawei SUN2000'],
    inverter_type: 'DC-coupled',
    backup_capable: true,
    mounting_type: 'Floor',
    dimensions_h_mm: 670,
    dimensions_w_mm: 600,
    dimensions_d_mm: 150,
    weight_kg: 70,
    ip_rating: 'IP66',
    operating_temp_min_c: -20,
    operating_temp_max_c: 60,
    price_per_module_eur: 2800,
    installation_cost_eur: 1000,
    warranty_years: 10,
    warranty_cycles: 6000,
    warranty_capacity_retention_pct: 70,
    has_app: true,
    has_energy_management: true,
    supports_solar: true,
    supports_grid_services: false,
    status: 'Available',
    release_year: 2021,
    certifications: ['CE', 'IEC 62619'],
    description: 'High-efficiency modular system with excellent thermal management and IP66 rating.',
    manufacturer_url: 'https://solar.huawei.com'
  },
  {
    slug: 'pylontech-force-l2',
    brand: 'Pylontech',
    model: 'Force L2',
    variant: null,
    production_location: 'China',
    production_country: 'China',
    module_capacity_kwh: 3.55,
    min_modules: 1,
    max_modules: 8,
    total_capacity_min_kwh: 3.55,
    total_capacity_max_kwh: 28.40,
    cell_technology: 'LFP',
    cycle_life: 6000,
    depth_of_discharge_pct: 95,
    efficiency_pct: 95.0,
    charge_power_kw: 3.7,
    discharge_power_kw: 3.7,
    continuous_power_kw: 3.7,
    peak_power_kw: 5.0,
    compatible_inverters: ['Victron', 'Goodwe', 'Deye', 'Growatt'],
    inverter_type: 'DC-coupled',
    backup_capable: false,
    mounting_type: 'Floor',
    dimensions_h_mm: 440,
    dimensions_w_mm: 420,
    dimensions_d_mm: 130,
    weight_kg: 37,
    ip_rating: 'IP20',
    operating_temp_min_c: -10,
    operating_temp_max_c: 50,
    price_per_module_eur: 1850,
    installation_cost_eur: 800,
    warranty_years: 10,
    warranty_cycles: 6000,
    warranty_capacity_retention_pct: 80,
    has_app: false,
    has_energy_management: false,
    supports_solar: true,
    supports_grid_services: false,
    status: 'Available',
    release_year: 2020,
    certifications: ['CE', 'IEC 62619'],
    description: 'Cost-effective modular LFP system with wide inverter compatibility.',
    manufacturer_url: 'https://www.pylontech.com.cn'
  },
  {
    slug: 'solaredge-energy-bank',
    brand: 'SolarEdge',
    model: 'Energy Bank',
    variant: null,
    production_location: 'China',
    production_country: 'China',
    module_capacity_kwh: 9.7,
    min_modules: 1,
    max_modules: 3,
    total_capacity_min_kwh: 9.7,
    total_capacity_max_kwh: 29.1,
    cell_technology: 'NMC',
    cycle_life: 5000,
    depth_of_discharge_pct: 90,
    efficiency_pct: 94.5,
    charge_power_kw: 5.0,
    discharge_power_kw: 5.0,
    continuous_power_kw: 5.0,
    peak_power_kw: 7.5,
    compatible_inverters: ['SolarEdge inverters'],
    inverter_type: 'DC-coupled',
    backup_capable: true,
    mounting_type: 'Floor',
    dimensions_h_mm: 1135,
    dimensions_w_mm: 656,
    dimensions_d_mm: 214,
    weight_kg: 120,
    ip_rating: 'IP55',
    operating_temp_min_c: -10,
    operating_temp_max_c: 50,
    price_per_module_eur: 6500,
    installation_cost_eur: 1800,
    warranty_years: 10,
    warranty_cycles: 5000,
    warranty_capacity_retention_pct: 70,
    has_app: true,
    has_energy_management: true,
    supports_solar: true,
    supports_grid_services: false,
    status: 'Available',
    release_year: 2023,
    certifications: ['CE', 'UL 9540'],
    description: 'Integrated battery solution optimized for SolarEdge solar systems with backup capability.',
    manufacturer_url: 'https://www.solaredge.com'
  },
  {
    slug: 'alpha-ess-smile-b3',
    brand: 'Alpha ESS',
    model: 'SMILE-B3',
    variant: null,
    production_location: 'China',
    production_country: 'China',
    module_capacity_kwh: 2.9,
    min_modules: 2,
    max_modules: 10,
    total_capacity_min_kwh: 5.8,
    total_capacity_max_kwh: 29.0,
    cell_technology: 'LFP',
    cycle_life: 6000,
    depth_of_discharge_pct: 90,
    efficiency_pct: 95.0,
    charge_power_kw: 3.0,
    discharge_power_kw: 3.0,
    continuous_power_kw: 3.0,
    peak_power_kw: 4.5,
    compatible_inverters: ['Alpha ESS inverters'],
    inverter_type: 'DC-coupled',
    backup_capable: true,
    mounting_type: 'Wall',
    dimensions_h_mm: 490,
    dimensions_w_mm: 420,
    dimensions_d_mm: 130,
    weight_kg: 30,
    ip_rating: 'IP65',
    operating_temp_min_c: -10,
    operating_temp_max_c: 55,
    price_per_module_eur: 1650,
    installation_cost_eur: 900,
    warranty_years: 10,
    warranty_cycles: 6000,
    warranty_capacity_retention_pct: 70,
    has_app: true,
    has_energy_management: true,
    supports_solar: true,
    supports_grid_services: false,
    status: 'Available',
    release_year: 2021,
    certifications: ['CE', 'IEC 62619'],
    description: 'Compact modular system with IP65 rating suitable for outdoor installation.',
    manufacturer_url: 'https://www.alpha-ess.com'
  },
  {
    slug: 'sungrow-sbr-hv',
    brand: 'Sungrow',
    model: 'SBR',
    variant: 'HV',
    production_location: 'China',
    production_country: 'China',
    module_capacity_kwh: 3.2,
    min_modules: 2,
    max_modules: 8,
    total_capacity_min_kwh: 6.4,
    total_capacity_max_kwh: 25.6,
    cell_technology: 'LFP',
    cycle_life: 6000,
    depth_of_discharge_pct: 90,
    efficiency_pct: 96.0,
    charge_power_kw: 3.3,
    discharge_power_kw: 3.3,
    continuous_power_kw: 3.3,
    peak_power_kw: 5.0,
    compatible_inverters: ['Sungrow SH-Series'],
    inverter_type: 'DC-coupled',
    backup_capable: true,
    mounting_type: 'Floor',
    dimensions_h_mm: 460,
    dimensions_w_mm: 445,
    dimensions_d_mm: 130,
    weight_kg: 35,
    ip_rating: 'IP65',
    operating_temp_min_c: -10,
    operating_temp_max_c: 55,
    price_per_module_eur: 1950,
    installation_cost_eur: 850,
    warranty_years: 10,
    warranty_cycles: 6000,
    warranty_capacity_retention_pct: 80,
    has_app: true,
    has_energy_management: true,
    supports_solar: true,
    supports_grid_services: false,
    status: 'Available',
    release_year: 2020,
    certifications: ['CE', 'IEC 62619'],
    description: 'High-efficiency modular LFP system with IP65 protection for flexible installation.',
    manufacturer_url: 'https://www.sungrowpower.com'
  },
  {
    slug: 'goodwe-lynx-home-u',
    brand: 'Goodwe',
    model: 'Lynx Home',
    variant: 'U',
    production_location: 'China',
    production_country: 'China',
    module_capacity_kwh: 3.1,
    min_modules: 1,
    max_modules: 6,
    total_capacity_min_kwh: 3.1,
    total_capacity_max_kwh: 18.6,
    cell_technology: 'LFP',
    cycle_life: 6000,
    depth_of_discharge_pct: 90,
    efficiency_pct: 95.5,
    charge_power_kw: 3.2,
    discharge_power_kw: 3.2,
    continuous_power_kw: 3.2,
    peak_power_kw: 4.8,
    compatible_inverters: ['Goodwe inverters'],
    inverter_type: 'DC-coupled',
    backup_capable: true,
    mounting_type: 'Floor',
    dimensions_h_mm: 440,
    dimensions_w_mm: 420,
    dimensions_d_mm: 150,
    weight_kg: 36,
    ip_rating: 'IP65',
    operating_temp_min_c: -10,
    operating_temp_max_c: 55,
    price_per_module_eur: 1700,
    installation_cost_eur: 750,
    warranty_years: 10,
    warranty_cycles: 6000,
    warranty_capacity_retention_pct: 70,
    has_app: true,
    has_energy_management: true,
    supports_solar: true,
    supports_grid_services: false,
    status: 'Available',
    release_year: 2021,
    certifications: ['CE', 'IEC 62619'],
    description: 'Compact modular battery with high efficiency and outdoor-capable IP65 rating.',
    manufacturer_url: 'https://www.goodwe.com'
  },
  {
    slug: 'fronius-solar-battery',
    brand: 'Fronius',
    model: 'Solar Battery',
    variant: null,
    production_location: 'Europe',
    production_country: 'Austria',
    module_capacity_kwh: 4.5,
    min_modules: 1,
    max_modules: 6,
    total_capacity_min_kwh: 4.5,
    total_capacity_max_kwh: 27.0,
    cell_technology: 'LFP',
    cycle_life: 6000,
    depth_of_discharge_pct: 90,
    efficiency_pct: 94.0,
    charge_power_kw: 4.5,
    discharge_power_kw: 4.5,
    continuous_power_kw: 4.5,
    peak_power_kw: 6.5,
    compatible_inverters: ['Fronius GEN24', 'Fronius Symo Hybrid'],
    inverter_type: 'DC-coupled',
    backup_capable: true,
    mounting_type: 'Wall',
    dimensions_h_mm: 730,
    dimensions_w_mm: 520,
    dimensions_d_mm: 225,
    weight_kg: 60,
    ip_rating: 'IP55',
    operating_temp_min_c: -10,
    operating_temp_max_c: 50,
    price_per_module_eur: 3400,
    installation_cost_eur: 1400,
    warranty_years: 10,
    warranty_cycles: 6000,
    warranty_capacity_retention_pct: 80,
    has_app: true,
    has_energy_management: true,
    supports_solar: true,
    supports_grid_services: false,
    status: 'Available',
    release_year: 2022,
    certifications: ['CE', 'VDE'],
    description: 'Austrian-made battery optimized for Fronius hybrid inverters with emergency power.',
    manufacturer_url: 'https://www.fronius.com'
  },
  {
    slug: 'kostal-piko-battery-li',
    brand: 'Kostal',
    model: 'PIKO Battery',
    variant: 'Li',
    production_location: 'Germany',
    production_country: 'Germany',
    module_capacity_kwh: 5.5,
    min_modules: 1,
    max_modules: 4,
    total_capacity_min_kwh: 5.5,
    total_capacity_max_kwh: 22.0,
    cell_technology: 'NMC',
    cycle_life: 6000,
    depth_of_discharge_pct: 90,
    efficiency_pct: 93.5,
    charge_power_kw: 5.5,
    discharge_power_kw: 5.5,
    continuous_power_kw: 5.5,
    peak_power_kw: 8.0,
    compatible_inverters: ['Kostal PLENTICORE'],
    inverter_type: 'DC-coupled',
    backup_capable: true,
    mounting_type: 'Floor',
    dimensions_h_mm: 1230,
    dimensions_w_mm: 540,
    dimensions_d_mm: 230,
    weight_kg: 95,
    ip_rating: 'IP20',
    operating_temp_min_c: 0,
    operating_temp_max_c: 40,
    price_per_module_eur: 4200,
    installation_cost_eur: 1600,
    warranty_years: 10,
    warranty_cycles: 6000,
    warranty_capacity_retention_pct: 80,
    has_app: true,
    has_energy_management: true,
    supports_solar: true,
    supports_grid_services: false,
    status: 'Available',
    release_year: 2019,
    certifications: ['CE', 'VDE'],
    description: 'German-engineered battery system with integrated emergency power functionality.',
    manufacturer_url: 'https://www.kostal-solar-electric.com'
  },
  {
    slug: 'fenecon-home',
    brand: 'Fenecon',
    model: 'Home',
    variant: null,
    production_location: 'Germany',
    production_country: 'Germany',
    module_capacity_kwh: 5.5,
    min_modules: 1,
    max_modules: 6,
    total_capacity_min_kwh: 5.5,
    total_capacity_max_kwh: 33.0,
    cell_technology: 'LFP',
    cycle_life: 6000,
    depth_of_discharge_pct: 95,
    efficiency_pct: 94.0,
    charge_power_kw: 10.0,
    discharge_power_kw: 10.0,
    continuous_power_kw: 10.0,
    peak_power_kw: 15.0,
    compatible_inverters: ['Fenecon (integrated)'],
    inverter_type: 'All-in-one',
    backup_capable: true,
    mounting_type: 'Floor',
    dimensions_h_mm: 1680,
    dimensions_w_mm: 600,
    dimensions_d_mm: 300,
    weight_kg: 180,
    ip_rating: 'IP20',
    operating_temp_min_c: 0,
    operating_temp_max_c: 40,
    price_per_module_eur: 6800,
    installation_cost_eur: 2400,
    warranty_years: 10,
    warranty_cycles: 6000,
    warranty_capacity_retention_pct: 80,
    has_app: true,
    has_energy_management: true,
    supports_solar: true,
    supports_grid_services: true,
    status: 'Available',
    release_year: 2020,
    certifications: ['CE', 'VDE'],
    description: 'German all-in-one system with high power output and virtual power plant capabilities.',
    manufacturer_url: 'https://fenecon.de'
  },
  {
    slug: 'qhome-ess-hyb-g3',
    brand: 'Q.HOME',
    model: 'ESS HYB-G3',
    variant: null,
    production_location: 'Europe',
    production_country: 'France',
    module_capacity_kwh: 4.8,
    min_modules: 1,
    max_modules: 6,
    total_capacity_min_kwh: 4.8,
    total_capacity_max_kwh: 28.8,
    cell_technology: 'LFP',
    cycle_life: 6000,
    depth_of_discharge_pct: 90,
    efficiency_pct: 95.0,
    charge_power_kw: 4.6,
    discharge_power_kw: 4.6,
    continuous_power_kw: 4.6,
    peak_power_kw: 7.0,
    compatible_inverters: ['Q.HOME+ inverter'],
    inverter_type: 'All-in-one',
    backup_capable: true,
    mounting_type: 'Floor',
    dimensions_h_mm: 1350,
    dimensions_w_mm: 580,
    dimensions_d_mm: 290,
    weight_kg: 110,
    ip_rating: 'IP20',
    operating_temp_min_c: 0,
    operating_temp_max_c: 40,
    price_per_module_eur: 4500,
    installation_cost_eur: 1700,
    warranty_years: 10,
    warranty_cycles: 6000,
    warranty_capacity_retention_pct: 70,
    has_app: true,
    has_energy_management: true,
    supports_solar: true,
    supports_grid_services: false,
    status: 'Available',
    release_year: 2021,
    certifications: ['CE', 'VDE'],
    description: 'European-made all-in-one system with integrated hybrid inverter and backup.',
    manufacturer_url: 'https://www.q-cells.eu'
  },
  {
    slug: 'solarwatt-battery-flex',
    brand: 'Solarwatt',
    model: 'Battery',
    variant: 'flex',
    production_location: 'Germany',
    production_country: 'Germany',
    module_capacity_kwh: 4.8,
    min_modules: 1,
    max_modules: 5,
    total_capacity_min_kwh: 4.8,
    total_capacity_max_kwh: 24.0,
    cell_technology: 'NMC',
    cycle_life: 5500,
    depth_of_discharge_pct: 90,
    efficiency_pct: 93.0,
    charge_power_kw: 4.6,
    discharge_power_kw: 4.6,
    continuous_power_kw: 4.6,
    peak_power_kw: 6.9,
    compatible_inverters: ['KACO', 'SMA', 'Fronius'],
    inverter_type: 'DC-coupled',
    backup_capable: false,
    mounting_type: 'Wall',
    dimensions_h_mm: 770,
    dimensions_w_mm: 545,
    dimensions_d_mm: 220,
    weight_kg: 68,
    ip_rating: 'IP20',
    operating_temp_min_c: 0,
    operating_temp_max_c: 40,
    price_per_module_eur: 4100,
    installation_cost_eur: 1500,
    warranty_years: 10,
    warranty_cycles: 5500,
    warranty_capacity_retention_pct: 80,
    has_app: true,
    has_energy_management: false,
    supports_solar: true,
    supports_grid_services: false,
    status: 'Available',
    release_year: 2020,
    certifications: ['CE', 'VDE', 'IEC 62619'],
    description: 'German-made modular battery with BMW battery cells and wide inverter compatibility.',
    manufacturer_url: 'https://www.solarwatt.de'
  },
  {
    slug: 'viessmann-vitocharge-vx3',
    brand: 'Viessmann',
    model: 'Vitocharge',
    variant: 'VX3',
    production_location: 'Germany',
    production_country: 'Germany',
    module_capacity_kwh: 7.6,
    min_modules: 1,
    max_modules: 4,
    total_capacity_min_kwh: 7.6,
    total_capacity_max_kwh: 30.4,
    cell_technology: 'LFP',
    cycle_life: 6000,
    depth_of_discharge_pct: 90,
    efficiency_pct: 94.5,
    charge_power_kw: 11.0,
    discharge_power_kw: 11.0,
    continuous_power_kw: 11.0,
    peak_power_kw: 16.5,
    compatible_inverters: ['Viessmann Vitocharge (integrated)'],
    inverter_type: 'All-in-one',
    backup_capable: true,
    mounting_type: 'Floor',
    dimensions_h_mm: 1640,
    dimensions_w_mm: 600,
    dimensions_d_mm: 285,
    weight_kg: 165,
    ip_rating: 'IP20',
    operating_temp_min_c: 0,
    operating_temp_max_c: 40,
    price_per_module_eur: 8200,
    installation_cost_eur: 2800,
    warranty_years: 10,
    warranty_cycles: 6000,
    warranty_capacity_retention_pct: 80,
    has_app: true,
    has_energy_management: true,
    supports_solar: true,
    supports_grid_services: false,
    status: 'Available',
    release_year: 2023,
    certifications: ['CE', 'VDE'],
    description: 'Premium German all-in-one system with high power output and smart home integration.',
    manufacturer_url: 'https://www.viessmann.de'
  }
];

console.log('🚀 Deploying Battery Storage to Supabase...\n');
console.log(`📡 URL: ${SUPABASE_URL}`);
console.log(`📦 Systems to deploy: ${storageData.length}\n`);

// Check table exists
const { data: check, error: checkErr } = await supabase
  .from('battery_storage')
  .select('id')
  .limit(1);

if (checkErr) {
  console.log('⚠️  Table does not exist yet. Creating via SQL...\n');

  // Read and execute DDL
  const sql = readFileSync('./supabase/migrations/003_battery_storage.sql', 'utf8');
  console.log('📄 Migration SQL loaded\n');
  console.log('❌ Cannot execute DDL via anon key.');
  console.log('\n📋 Please run the DDL manually in Supabase dashboard:');
  console.log('   1. Open SQL Editor');
  console.log('   2. Paste contents of: supabase/migrations/003_battery_storage.sql');
  console.log('   3. Run the CREATE TABLE statements');
  console.log('   4. Then run this script again\n');
  process.exit(1);
}

console.log('✅ Table exists!\n');

// Check existing data
const { count } = await supabase
  .from('battery_storage')
  .select('*', { count: 'exact', head: true });

console.log(`📊 Current: ${count || 0} systems`);

if (count > 0) {
  console.log('⚠️  Data exists. Clearing...\n');
  const { error: delErr } = await supabase
    .from('battery_storage')
    .delete()
    .neq('id', '00000000-0000-0000-0000-000000000000');

  if (delErr) {
    console.log('⚠️  Could not clear (might need RLS update)');
  } else {
    console.log('✅ Cleared!\n');
  }
}

// Insert data
console.log(`🚀 Inserting ${storageData.length} systems...\n`);

const { data, error } = await supabase
  .from('battery_storage')
  .insert(storageData)
  .select();

if (error) {
  console.error('❌ Error:', error.message);
  console.error('Code:', error.code);
  if (error.code === '42501') {
    console.log('\n⚠️  Permission denied. RLS policy might need update.');
    console.log('Run this in SQL Editor:\n');
    console.log(`DROP POLICY IF EXISTS "Allow inserts" ON battery_storage;
CREATE POLICY "Allow inserts" ON battery_storage
  FOR INSERT WITH CHECK (true);`);
  }
  process.exit(1);
}

console.log(`✅ Inserted ${data?.length || 0} systems!\n`);

// Verify
const { count: final } = await supabase
  .from('battery_storage')
  .select('*', { count: 'exact', head: true });

console.log(`📊 Final: ${final} systems in database\n`);
console.log('🎉 Migration complete!');
console.log('\n🔗 Visit: http://localhost:5173/storage\n');
